name: tvbox build

on:
  workflow_dispatch:
    inputs:
      author:
        description: 'author'
        required: true
        type: choice
        options:
        - 'q215613905'
        - 'takagen99'
        - 'chengxue2020'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone source code
        run: |
          if [ "${{ inputs.author }}" == "q215613905" ]; then
            git clone --depth 1 https://github.com/q215613905/TVBoxOS.git boxdir
            ln -s tvbox tvboxpatch
          elif [ "${{ inputs.author }}" == "takagen99" ]; then
            git clone --depth 1 https://github.com/takagen99/Box.git boxdir
            sed -i 's|applicationId .*|applicationId '\''com.github.tvbox.osc.muziling'\''|g' boxdir/app/build.gradle
            sed -i 's|<string name="app_source">.*|<string name="app_source">https://agit.ai/Yoursmile7/TVBox/raw/branch/master/XC.json</string>|g' boxdir/app/src/main/res/values-zh/strings.xml
            ln -s tvbox-takagen99 tvboxpatch
            cp -f tvboxpatch/film.png boxdir/app/src/main/res/drawable/app_icon.png
          else
            git clone --depth 1 https://github.com/chengxue2020/takagen99.git boxdir
            sed -i 's|applicationId .*|applicationId '\''com.github.tvbox.osc.muziling'\''|g' boxdir/app/build.gradle
            sed -i 's|<string name="app_source">.*|<string name="app_source">https://agit.ai/Yoursmile7/TVBox/raw/branch/master/XC.json</string>|g' boxdir/app/src/main/res/values-zh/strings.xml
            ln -s tvbox-takagen99 tvboxpatch
            cp -f tvboxpatch/film.png boxdir/app/src/main/res/drawable/app_icon.png
          fi
          #sed -i 's/putDefault(HawkConfig.HOME_REC.*/putDefault(HawkConfig.HOME_REC, 1);/g' boxdir/app/src/main/java/com/github/tvbox/osc/base/App.java
          #sed -i 's/urlBean.infoList = infoList;/urlBean.infoList = infoList;video.sourceKey=vod_play_from;/g' boxdir/app/src/main/java/com/github/tvbox/osc/bean/AbsJson.java

          #sed -i 's/annotation:1.3.0/annotation:1.5.0/g' boxdir/player/build.gradle
          #sed -i 's/:dkplayer-ui:3.3.5/:dkplayer-ui:3.3.7/g' boxdir/player/build.gradle
          #sed -i 's/:2.14.2/:2.18.3/g' boxdir/player/build.gradle
          #wget https://raw.githubusercontent.com/Doikki/DKVideoPlayer/3.3.7/dkplayer-players/exo/src/main/java/xyz/doikki/videoplayer/exo/ExoMediaSourceHelper.java -q --no-check-certificate -O boxdir/player/src/main/java/xyz/doikki/videoplayer/exo/ExoMediaSourceHelper.java
          #wget https://raw.githubusercontent.com/Doikki/DKVideoPlayer/3.3.7/dkplayer-players/exo/src/main/java/xyz/doikki/videoplayer/exo/ExoMediaPlayerFactory.java -q --no-check-certificate -O boxdir/player/src/main/java/xyz/doikki/videoplayer/exo/ExoMediaPlayerFactory.java
          #wget https://raw.githubusercontent.com/Doikki/DKVideoPlayer/3.3.7/dkplayer-players/exo/src/main/java/xyz/doikki/videoplayer/exo/ExoMediaPlayer.java -q --no-check-certificate -O boxdir/player/src/main/java/xyz/doikki/videoplayer/exo/ExoMediaPlayer.java
          #sed -i 's/compileSdkVersion .*/compileSdkVersion 33/g' boxdir/player/build.gradle
          #sed -i 's/minSdkVersion .*/minSdkVersion 21/g' boxdir/player/build.gradle
          sed -i 's/exoVersion = "2.16.0"/exoVersion = "2.18.3"/g' boxdir/build.gradle
          sed -i 's/annotation:1.3.0/annotation:1.5.0/g' boxdir/app/build.gradle
          sed -i 's/:dkplayer-ui:3.3.5/:dkplayer-ui:3.3.7/g' boxdir/app/build.gradle

          sed -i 's/compileSdkVersion .*/compileSdkVersion 33/g' boxdir/app/build.gradle
          sed -i 's/compileSdkVersion .*/compileSdkVersion 33/g' boxdir/quickjs/build.gradle
          sed -i 's/minSdkVersion .*/minSdkVersion 21/g' boxdir/app/build.gradle
          sed -i 's/minSdkVersion .*/minSdkVersion 21/g' boxdir/quickjs/build.gradle
          sed -i 's/import okhttp3.internal.Version;/import okhttp3.internal.Util;/g' boxdir/app/src/main/java/com/github/tvbox/osc/util/OkGoHelper.java
          sed -i 's/Version.userAgent()/Util.userAgent/g' boxdir/app/src/main/java/com/github/tvbox/osc/util/OkGoHelper.java
          sed -i ':label;N;s/for (int i = 1; i < failures.size(); i++) {\n            Util.addSuppressedIfPossible(unknownHostException, failures.get(i));\n        }/Util.withSuppressed(unknownHostException, failures);/;b label' boxdir/app/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.java
          sed -i 's/Platform.get().log(Platform.WARN, "Incorrect protocol: " + response.protocol(), null);/Platform.get().log("Incorrect protocol: " + response.protocol(), Platform.WARN, null);/g' boxdir/app/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.java
          sed -i 's/PublicSuffixDatabase.get()/PublicSuffixDatabase.Companion.get()/g' boxdir/app/src/main/java/okhttp3/dnsoverhttps/DnsOverHttps.java
          sed -i 's/com.squareup.okhttp3:okhttp:3.12.1/com.squareup.okhttp3:okhttp:4.10.0/g' boxdir/app/build.gradle
          sed -i 's/com.squareup.okio:okio:2.6.0/com.squareup.okio:okio:2.10.0/g' boxdir/app/build.gradle

          cd boxdir
          sudo -E apt-get -y install dos2unix
          dos2unix ../tvboxpatch/*.patch
          dos2unix app/src/main/java/com/github/tvbox/osc/ui/activity/HomeActivity.java
          find -L ../tvboxpatch -type f -iname '*.patch' -print0|xargs -n1 -0 patch -p 1 --no-backup-if-mismatch -i

      - name: Build with Gradle
        run: |
          cd boxdir
          chmod +x gradlew
          ./gradlew assemblerelease --build-cache --parallel --daemon --stacktrace --warning-mode all

#      - name: Prepare App
#        run: |
#          mkdir -p ${{ github.workspace }}/apk/
#          for file in `find ~ -name "*.apk" -print`; do
#            mv "$file" ${{ github.workspace }}/apk/
#          done
#      - name: Upload App To Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: com.github.tvbox.osc
#          path: ${{ github.workspace }}/apk/*

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v3
        with:
          name: com.github.tvbox.osc
          path: boxdir/app/build/outputs/apk
